# -*- coding: utf-8 -*-
"""Projeto1_Calculadora_inteligente.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UwnoTWtasUS2FX-_hUj6oJToP2D_bzdQ

# Calculadora inteligente 🔢


**Aluna:** Walessa Barcellos

**Data:** 03/11/2024



## ↪ Passo a passo:

* Utilize o comando 'input' para receber ao menos 2 números de entrada do usuário;

* Converta os valores recebidos pelo usuário para número inteiro (int) ou ponto flutuante (float);

* Implemente ao menos 4 operações matemáticas em seu código;

* Adicione um laço de repetição ou uma condicional. Por exemplo: você pode permitir que o usuário escolha qual operação realizar ou criar um loop que permita ao usuário realizar várias operações consecutivas;

* Utilize o comando 'print' para exibir o resultado da operação matemática.
"""

# Laço de repetição para permitir várias operações
while True:
    # Recebe os números do usuário
    num1 = float(input("Por favor, insira o primeiro número: "))
    num2 = float(input("Por favor, insira o segundo número: "))

    # Mostra as opções de operações
    print("Escolha uma operação:")
    print("1. Soma")
    print("2. Subtração")
    print("3. Multiplicação")
    print("4. Divisão")
    print("5. Sair")

    # Recebe a opção do usuário
    opcao = input("Digite o número da operação desejada (1-5): ")

    # Verifica se o usuário deseja sair
    if opcao == '5':
        print("Saindo do programa. Até logo!")
        break

    # Verifica se a opção é válida
    if opcao not in ('1', '2', '3', '4'):
        print("Opção inválida! Tente novamente.\n")
        continue

    # Converte a opção para inteiro
    opcao = int(opcao)

    # Realiza o cálculo e exibe o resultado
    if opcao == 1:
        resultado = num1 + num2
        print(f"O resultado da soma é: {resultado}\n")
    elif opcao == 2:
        resultado = num1 - num2
        print(f"O resultado da subtração é: {resultado}\n")
    elif opcao == 3:
        resultado = num1 * num2
        print(f"O resultado da multiplicação é: {resultado}\n")
    elif opcao == 4:
        if num2 != 0:
            resultado = num1 / num2
            print(f"O resultado da divisão é: {resultado}\n")
        else:
            print("Erro: Divisão por zero!\n")
